version: '3'
services:
  bot:
    build: .
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 120 1'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
      - '--requirepass ${REDIS_PASSWORD}'
    volumes:
      - ./redis_data:/data
    ports:
      - "6381:${REDIS_PORT}"  
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1ms
      timeout: 30s
      retries: 10000