name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          debug: true
          script: |
            whoami
            cd ~/Bot
            git reset --hard
            git pull origin master
            cat << EOF > .env
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}

            RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }}
            RABBITMQ_PORT=${{ secrets.RABBITMQ_PORT }}
            RABBITMQ_USER=${{ secrets.RABBITMQ_DEFAULT_USER }}
            RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_DEFAULT_PASS  }}
            RABBITMQ_QUEUE=${{ secrets.RABBITMQ_QUEUE }}

            USER_SERVICE_HOST=${{ secrets.HOST }}
            USER_SERVICE_PORT=${{ secrets.USER_SERVICE_PORT }}
            EOF
            docker compose -f deploy.yml up --build -d --force-recreate